name: Testing Suite
on: [push, pull_request]

jobs:
    build-and-test-linux:
        services:
            mongodb:
                image: mongo:4.2
                ports:
                    - 27017:27017
        runs-on: ${{ matrix.operating-system }}
        env:
            extensions: mbstring, intl, json, phalcon4, xdebug
            key: cache-v0.0.2
        strategy:
            fail-fast: false
            matrix:
                operating-system: [ubuntu-latest]
                php-versions: ['7.2', '7.3', '7.4']

        name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
        steps:

            - name: Git checkout
              uses: actions/checkout@v2-beta
              with:
                  fetch-depth: 1

            - name: Get Composer Cache Directory
              id: composer-cache
              run: |
                  echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Setup Cache
              uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

            - name: Setup Composer Token
              run: |
                  # To increase the Composer rate limit we're use GitHub authentication
                  if [ -n "${{ secrets.COMPOSER_TOKEN }}" ]; then
                    composer config github-oauth.github.com "${{ secrets.COMPOSER_TOKEN }}"
                  fi

            - name: Setup PHP
              uses: shivammathur/setup-php@v1
              with:
                  ini-values: apc.enable_cli=on, session.save_path=/tmp
                  php-version: ${{ matrix.php-versions }}
                  extensions: ${{ env.extensions }}
                  tools: pecl

            - name: Install packages
              run: composer install --prefer-dist

            - name: Setup tests
              run: |
                  cp tests/_ci/.env.default .env
                  vendor/bin/codecept build
            - name: Run integration tests
              run: vendor/bin/codecept run --ext DotReporter integration --coverage --coverage-xml
