name: Testing Suite
on: [push, pull_request]

jobs:
    build-and-test-linux:
        services:
            mongodb:
                image: mongo:4.2
                ports:
                    - 27017:27017
        runs-on: ${{ matrix.operating-system }}
        env:
            extensions: mbstring, intl, json, phalcon4, xdebug
            key: cache-v0.0.2
        strategy:
            fail-fast: false
            matrix:
                operating-system: [ubuntu-latest]
                php-versions: ['7.2', '7.3', '7.4']

        name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
        steps:

            - name: Git checkout
              uses: actions/checkout@v2-beta
              with:
                  fetch-depth: 1

            - name: Setup cache environment
              id: cache-env
              uses: shivammathur/cache-extensions@v1
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: ${{ env.extensions }}
                  key: ${{ env.key }}

            - name: Cache extensions
              uses: actions/cache@v1
              with:
                  path: ${{ steps.cache-env.outputs.dir }}
                  key: ${{ steps.cache-env.outputs.key }}
                  restore-keys: ${{ steps.cache-env.outputs.key }}

            - name: Setup PHP
              uses: shivammathur/setup-php@v1
              with:
                  ini-values: apc.enable_cli=on, session.save_path=/tmp
                  php-version: ${{ matrix.php-versions }}
                  extensions: ${{ env.extensions }}
                  tools: pecl

            - name: Get Composer Cache Directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache composer dependencies
              uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install packages
              run: composer install --prefer-dist --no-suggest

            - name: Setup tests
              run: |
                  cp tests/_ci/.env.default .env
                  vendor/bin/codecept build
            - name: Run integration tests
              run: vendor/bin/codecept run --ext DotReporter integration --coverage --coverage-xml
